### ISSUE TITLE
anonfile-api update should have broken backward compatibility

### ISSUE THREAD

**Issue by nstrydom2** [freakingrocky/thoryvos#2]
I have recently release an update to the <anonfiles.com> unofficial [API](https://github.com/nstrydom2/anonfile-api). I have looked over your code and at first glance it looks like you should only have to update 2 lines. Sorry about the inconvenience.

**Comment by freakingrocky** [comment]
Hey, Thanks for the update. Really appreciate it!!!

**Comment by freakingrocky** [comment]
UPDATED thoryvos_transfer,py
